import Head from 'next/head'
import styled from "styled-components";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>
      </main>

      
    </div>
  )
}

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;  
`;
